title: STUXNET
description: FADE SCATTER REPLICATE
baseurl: /
url: https://stuxnet.me
permalink: pretty
sort_by: year, month
markdown: kramdown
kramdown:
  parse_block_html: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
feed:
  path: feed.xml