title: STUXNET
description: CIPHER SUITE (demo) OUT NOW
baseurl: /
url: https://stuxnet.me
permalink: pretty
sort_by: year, month
markdown: kramdown
theme: minima
kramdown:
  parse_block_html: true
plugins:
  - jekyll-feed
  - jekyll-sitemap
feed:
  path: feed.xml
include: ['_pages']
collections_dir: collections
collections:
  - examples